// src/components/LoginForm.tsx
// src/components/LoginForm.tsx
'use client';

import { useState } from 'react';
import ButtonWithAnimatedBG from './ButtonWithAnimatedBG';
import AnimatedInput from './AnimatedInput';
import { useRouter } from 'next/navigation';

export default function LoginForm() {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const router = useRouter();
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);

    try {
      if (!window.electron || !window.electron.ipcRenderer) {
        throw new Error('Electron IPC not available');
      }
      const res = await window.electron.ipcRenderer.invoke('login', { username, password }) as { 
        success: boolean; 
        sessionId?: string; 
        error?: string 
      };

      if (res.success && res.sessionId) {
        // Store session ID for use in other IPC calls
        localStorage.setItem('clipSessionId', res.sessionId);
        router.push('/dashboard');
      } else {
        alert(res.error || 'Login failed');
      }
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : 'Login failed';
      alert(message);
    }
    setLoading(false);
  };

  return (
    <div className="relative">
      {/* Beautiful Glassmorphism Background */}
      <div
        className="absolute inset-0 -z-10"
        style={{
          background: `
            linear-gradient(135deg, 
              rgba(255, 255, 255, 0.15) 0%, 
              rgba(255, 255, 255, 0.08) 50%, 
              rgba(147, 197, 253, 0.12) 100%
            )
          `,
          backdropFilter: 'blur(20px)',
          borderRadius: '20px',
          border: '1px solid rgba(255, 255, 255, 0.2)',
          boxShadow: `
            0 8px 32px rgba(0, 0, 0, 0.1),
            inset 0 1px 0 rgba(255, 255, 255, 0.3),
            0 0 60px rgba(147, 197, 253, 0.15)
          `
        }}
      />

      {/* Subtle shimmer animation */}
      <div
        className="absolute inset-0 -z-5 pointer-events-none"
        style={{
          background: 'linear-gradient(135deg, transparent 30%, rgba(255,255,255,0.15) 50%, transparent 70%)',
          backgroundSize: '200% 200%',
          animation: 'formShimmer 10s linear infinite',
          borderRadius: '20px'
        }}
      />

      <form
        onSubmit={handleSubmit}
        className="flex flex-col items-center justify-center space-y-5 px-8 py-8 relative z-10"
      >
        <AnimatedInput
          type="text"
          placeholder="Identificador de estudante"
          value={username}
          onChange={(e) => setUsername(e.target.value)}
          color="pink"
          required
        />
        <AnimatedInput
          type="password"
          placeholder="Senha"
          value={password}
          onChange={(e) => setPassword(e.target.value)}
          color="blue"
          required
        />
        <ButtonWithAnimatedBG loading={loading} />
      </form>
    </div>
  );
}

// vue-app/src/components/LoginForm.vue
<template>
  <div class="bg-white rounded-2xl shadow-xl p-8 border border-gray-100">
    <form @submit.prevent="handleSubmit" class="space-y-6">
      <!-- Username Input -->
      <div>
        <label for="username" class="block text-sm font-semibold text-gray-700 mb-2">
          Identificador de estudante
        </label>
        <div class="relative">
          <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
            <svg class="h-5 w-5 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
            </svg>
          </div>
          <input
            id="username"
            type="text"
            v-model="username"
            required
            class="w-full pl-10 pr-4 py-3 bg-gray-50 border border-gray-200 rounded-xl focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none transition-all"
            placeholder="ex: j.pd"
          />
        </div>
      </div>

      <!-- Password Input -->
      <div>
        <label for="password" class="block text-sm font-semibold text-gray-700 mb-2">
          Senha
        </label>
        <div class="relative">
          <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
            <svg class="h-5 w-5 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
            </svg>
          </div>
          <input
            id="password"
            type="password"
            v-model="password"
            required
            class="w-full pl-10 pr-4 py-3 bg-gray-50 border border-gray-200 rounded-xl focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none transition-all"
            placeholder="••••••••"
          />
        </div>
      </div>

      <!-- Submit Button -->
      <button
        type="submit"
        :disabled="loading"
        class="w-full bg-gradient-to-r from-blue-600 to-indigo-600 text-white font-semibold py-3 px-4 rounded-xl hover:from-blue-700 hover:to-indigo-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 disabled:opacity-50 disabled:cursor-not-allowed transition-all transform hover:scale-[1.02] active:scale-[0.98] shadow-lg shadow-blue-500/30"
      >
        <span v-if="loading" class="flex items-center justify-center">
          <svg class="animate-spin -ml-1 mr-3 h-5 w-5 text-white" fill="none" viewBox="0 0 24 24">
            <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
            <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
          </svg>
          Entrando...
        </span>
        <span v-else>Entrar</span>
      </button>
    </form>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { useRouter } from 'vue-router';
import { invoke } from '@tauri-apps/api/core';

interface LoginResponse {
  success: boolean;
  session_id?: string;
  error?: string;
}

const router = useRouter();
const username = ref('');
const password = ref('');
const loading = ref(false);

const handleSubmit = async () => {
  loading.value = true;

  try {
    const res = await invoke<LoginResponse>('login', { 
      username: username.value, 
      password: password.value 
    });

    if (res.success && res.session_id) {
      localStorage.setItem('clipSessionId', res.session_id);
      router.push('/dashboard');
    } else {
      alert(res.error || 'Login failed');
    }
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : 'Login failed';
    alert(message);
  }
  loading.value = false;
};
</script>
